name: Validate Rules

on:
  push:
    paths:
      - ".cursor/rules/**"
  pull_request:
    paths:
      - ".cursor/rules/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Validate rule structure
        run: python -m src.validation.rules

      - name: Check rule conflicts
        run: python -m src.validation.conflicts

      - name: Generate summaries
        run: python -m src.validation.summary

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: validation-report
          path: |
            reports/validation.md
            reports/conflicts.md
            reports/summary.md
